# Site
name: "Chez Beber"
title: "Chez Beber"
description: "Bienvenue, tu peux retrouver ici tous les recettes de la famille. N'hésite pas à contribuer en ajoutant les tiennes !"
logo: 'assets/images/vb_black.png'
favicon: 'assets/images/vb_black.png'
baseurl: /mediumish-theme-jekyll
disqus: 'demowebsite' 
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  vincent:
    name: Vincent
    display_name: Vincent    
    avatar: 'assets/images/vincent.jpg'
    email: vincent.berthet42@gmail.com
    web: https://realvincentberthet.github.io/vberthet/
    description: "@edsfrTODO vincent description"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images 
lazyimages: "enabled"

exclude: [ LICENSE.txt, README.md, Gemfile, Gemfile.lock]
