# Site
name: "Chez Bebert"
title: "Chez Bebert"
description: "Bienvenue, tu peux retrouver ici toutes les astuces des Bebert. N'hésite pas à contribuer en ajoutant les tiennes !"
logo: 'assets/images/template/logo.png'
favicon: 'assets/images/template/logo.png'
#baseurl: ""
baseurl: https://realvincentberthet.github.io/jekyll-site/
#disqus: 'demowebsite' 
#mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  vincent:
    name: Bichente  
    avatar: 'assets/images/avatars/vincent.jpg'
    email: vincent.berthet42@gmail.com
    description: "Larbin commis d'office"
  moman:
    name: Moman
    avatar: 'assets/images/avatars/moman.jpg'
    email: marie.joelle@hotmail.fr
    description: "Maître étoilée"
  popa:
    name: Popa  
    avatar: 'assets/images/avatars/popa.jpg'
    description: "Réincarnation de Mac Giver"
  mamie:
    name: Mamie Glue  
    avatar: 'assets/images/avatars/mamie.jpg'
    description: "Oh mamie, mamie glueeee"
  cedric:
    name: Dieu
    avatar: 'assets/images/avatars/cedric.jpg'
    email: cedric.berthet@gmail.com
    description: "Dieu, simple, basique"
  carole:
    name: Carole
    avatar: 'assets/images/avatars/carole.jpg'
    email: carole.cerdan@gmail.com
    description: "Spécialiste foie gras officielle"
  elise:
    name: Elise
    avatar: 'assets/images/avatars/elise.jpg'
    description: "Le monstre"
  guillaume:
    name: Guiguilamoroso
    avatar: 'assets/images/avatars/guillaume.jpg'
    email: guillaume.berthet@gmail.com
    description: ""
  rita:
    name: Rita di Portuguesh
    avatar: 'assets/images/avatars/rita.jpg'
    description: "CR7 > Messi"
  manon:
    name: Nounouille
    avatar: 'assets/images/avatars/manon.jpg'
    email: manon.berthet@gmail.com
    description: "Aime les plantes"

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/

# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images 
lazyimages: "enabled"

exclude: [ LICENSE.txt, README.md, Gemfile, Gemfile.lock]
